{% set name = "napari-philow" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-PHILOW-{{ version }}.tar.gz
  sha256: 025509342dcbc40a7824ea72fa7c9f915621aa61a0c94d3f85bc61ba743a1e67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask-image
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - pandas
    - python >=3.7
    - scikit-image
    - pytorch
    - torchvision

test:
  imports:
    - napari_philow
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neurobiology-ut/PHILOW
  summary: PHILOW is an interactive deep learning-based platform for 3D datasets
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
